### ISSUE TITLE
Documentation/Wiki?

### ISSUE THREAD

**Issue by jimmyjxiao** [hippiehunter/SnooDom#2]
Is there documentation on how to use this for UWP?

**Comment by hippiehunter** [comment]
I don't have any real documentation but here is approximately how i use it in SnooStream

this goes where you want to use it in the xaml, where body is either a string (making plain text or Body is a SnooDom.SnooDom instance
```
<snoodom:MarkdownControl Markdown="{x:Bind Body}"
                        StyleProvider="{StaticResource markdownHelpers}"
                        CommandFactory="{StaticResource markdownHelpers}"
                        HorizontalAlignment="Stretch"/>
```
here is an implementation of MarkdownHelpers 
https://github.com/hippiehunter/Baconography/blob/uwp/SnooStream/Common/MarkdownHelpers.cs

in my case i needed to pool memory allocation across a large set of markdown objects so its set up to precreate a SnooDom.SimpleSessionMemoryPool and pass that to all related calls to SnooDom.SnooDom.MarkdownToDOM(body, markdownMemoryPool)

The SnooDom.SnooDom object that comes out from the call to MarkdownToDOM can then be bound to a MarkdownControl. Let me know if you have any further questions, I will consider creating some wiki pages for this if i know other people are using it.

**Comment by zowpowow** [comment]
Thank you for responding. I don't quite understand how to implement INavigationContext used in the Markdownhelpers in C++/CX.

**Comment by hippiehunter** [comment]
Here is a simpler example in C++/CX

```
public ref class MarkdownHelper sealed : ICommandFactory, IStyleProvider
    {
    public:
        virtual Windows::Foundation::TypedEventHandler<Windows::UI::Xaml::Documents::Hyperlink^, Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>^ MakeLinkCommand(Platform::String^ url)
        {
            return ref new Windows::Foundation::TypedEventHandler<Windows::UI::Xaml::Documents::Hyperlink^, Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^>([](Windows::UI::Xaml::Documents::Hyperlink^ link, Windows::UI::Xaml::Documents::HyperlinkClickEventArgs^ bla) -> void
            {
                //Do whatever navigation needs to happen
            });
        }

        virtual property Windows::UI::Xaml::Style^ RichTextBlockStyle { Windows::UI::Xaml::Style^ get() { return dynamic_cast<Windows::UI::Xaml::Style^>(Application::Current->Resources->Lookup("MarkdownRichTextStyle")); } }
        virtual property Windows::UI::Xaml::Style^ TextBlockStyle { Windows::UI::Xaml::Style^ get() { return dynamic_cast<Windows::UI::Xaml::Style^>(Application::Current->Resources->Lookup("MarkdownTextStyle")); } }
        virtual property Windows::UI::Xaml::Style^ BorderStyle { Windows::UI::Xaml::Style^ get() { return dynamic_cast<Windows::UI::Xaml::Style^>(Application::Current->Resources->Lookup("MarkdownBorderStyle")); } }
        virtual property Windows::UI::Xaml::Style^ RunStyle { Windows::UI::Xaml::Style^ get() { return dynamic_cast<Windows::UI::Xaml::Style^>(Application::Current->Resources->Lookup("MarkdownRunStyle")); } }
    };
```

**Comment by zowpowow** [comment]
Thanks for responding.  Hi, I'm sorry for getting back to you so late, I haven't had a chance to look at this until now. Does the markdown argument take Platform::Strings? Your original reply made it seem like it did, but when I x:Bind it to a String^ property, but when I x:Bind it to the control, I get a "cannot find resource with given key" exception.

**Comment by hippiehunter** [comment]
the currently checked in source will take a platform::string as the markdown argument (this is plain text, not really for actual markdown) "cannot find resource with given key" is likely to be something to do with your styles. If you're using the implementation above then things like MarkdownRichTextStyle/MarkdownTextStyle/MarkdownBorderStyle/MarkdownRunStyle need to exist in your app.xaml

**Comment by zowpowow** [comment]
Got it working, thanks!
